### PR TITLE
consider also relations - it will display opening hours on multipolygons

### LINKED ISSUE #40: opening_hours on a fine multipolygon are not appearing
https://www.openstreetmap.org/relation/4121283#map=16/50.0991/19.9825 is tagged but it is not appearing on http://ypid.de/~osm/?zoom=15&lat=50.09999&lon=19.98186&layers=B0T&tags=opening_hours&filter=none

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes #40 

Untested due to #46

### CODE REVIEW

**Comment by matkoniecz** [comment]
I fixed #46, but it still untested as I ended using my opening_hours time for this morning for other work visible in other PRs.

**Comment by matkoniecz** [comment]
@ypid Now it is improved so it works, tested and it seems to work.

**Comment by ypid** [comment]
Thanks! I will test it later and give it a try and deploy.

**Comment by matkoniecz** [comment]
Thaks!

**Comment by ypid** [comment]
Works nicely, thanks! Deployed.

https://openingh.ypid.de/?zoom=18&lat=51.33288&lon=12.37499&layers=B0T&filter=none&tags=opening_hours

**Pull request merged**
